package edu.jsu.mcis.cs350;

import java.beans.PropertyChangeEvent;
import javax.swing.text.DefaultCaret;

public class Lab3View extends javax.swing.JFrame implements AbstractView {
    
    private final Lab3Controller controller;

    public Lab3View(Lab3Controller controller) {

        super("CS 350 Lab #3");
        
        this.controller = controller;
        
        initComponents();
        
        DefaultCaret caret = (DefaultCaret)jOutputTextArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        
    }
    
    private void addElement() {
    
        try {
            controller.addElement(jInputField.getText());
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void removeElement() {
    
        try {
            controller.removeElement();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    @Override
    public void modelPropertyChange(final PropertyChangeEvent evt) {
        
        if ( evt.getPropertyName().equals(Lab3Controller.OUTPUT_MESSAGE) ) {
            
            String newStringValue = evt.getNewValue().toString();
            
            StringBuilder s = new StringBuilder();
            s.append(newStringValue);
            s.append(System.lineSeparator()).append(System.lineSeparator());
            
            jOutputTextArea.append(s.toString());
        
        }
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jInputField = new javax.swing.JTextField();
        jInputAddButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOutputTextArea = new javax.swing.JTextArea();
        jInputRemoveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("New Element:");

        jInputAddButton.setText("Add");
        jInputAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputAddButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jOutputTextArea.setColumns(20);
        jOutputTextArea.setRows(5);
        jScrollPane1.setViewportView(jOutputTextArea);

        jInputRemoveButton.setText("Remove");
        jInputRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInputField, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInputAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInputRemoveButton)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInputAddButton)
                    .addComponent(jInputRemoveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInputAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputAddButtonActionPerformed
        addElement();
    }//GEN-LAST:event_jInputAddButtonActionPerformed

    private void jInputRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInputRemoveButtonActionPerformed
        removeElement();
    }//GEN-LAST:event_jInputRemoveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jInputAddButton;
    private javax.swing.JTextField jInputField;
    private javax.swing.JButton jInputRemoveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jOutputTextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
